# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name:  Wpf Continuous Integration

# https://github.com/microsoft/github-actions-for-desktop-apps/blob/main/.github/workflows/ci.yml
# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  setup-version:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
  #build:
    #strategy:
      matrix:
        targetplatform: [x86, x64]
        configuration: [Debug, Release]
        #operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        operating-system: [windows-latest]
        #dotnet-version: ['2.1', '2.2' , '2.2.103', '3.0', '3.1', '3.1.x' , '5.0']
        dotnet-version: ['2.2' ,'3.1.x' , '5.0']
        #python: [2.7, 3.5, 3.6, 3.7, 3.8]
        #experimental: [false]

    #runs-on: windows-latest

    env:
      Solution_Path: SmartMove.sln
      Wpf_Project_Path: SmartMove\SmartMove.csproj
      Actions_Allow_Unsecure_Commands: true # Allows AddPAth and SetEnv commands

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    # Use Nerdbank.GitVersioning to set version variables: https://github.com/AArnott/nbgv
    - name: Use Nerdbank.GitVersioning to set version variables
      uses: aarnott/nbgv@v0.3
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        DOTNET_CLI_TELEMETRY_OPTOUT : 'true'
        DISABLEOUTOFPROCTASKHOST : '1'
      with:
        setAllVars: true
      
        

    # Install the .NET Core workload
    - name: Install .NET Core ${{ matrix.dotnet-version }}
      #uses: actions/setup-dotnet@v1
      uses: actions/setup-dotnet@v1.6.0
      with:
        #dotnet-version: '3.1.302'
        dotnet-version: ${{ matrix.dotnet-version }}
    #- name: Clean Certificate
    #  env:
    #    DOTNET_CLI_TELEMETRY_OPTOUT : 'true'
    #  run: |
    #      dotnet dev-certs https --clean -q 
    #      dotnet dev-certs https --trust -q 
          
    #- name: Install dependencies
    #  run: dotnet add package Newtonsoft.Json --version 12.0.1

    - name: Display dotnet version
      run: dotnet --version
      
    # Add  MsBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget install
      run: nuget install JetBrains.System.Windows.Interactivity

      
    # Build the Windows Application Packaging project
    - name: Build the Windows Application Packaging Project ${{ $env:Solution_Path }}
      run: msbuild $env:Solution_Path /p:Platform=$env:AnyPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle
      env:
        AppxBundle: Never
        BuildMode: SideloadOnly
        Configuration: ${{ matrix.configuration }}
        AnyPlatform: "Any CPU"

