# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build DotNET35
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\pathtoyoursolutionorproject
     
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
           
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
         
      - name: Restore NuGet Packages
        run: nuget restore SmartMove.sln
     
      - name: Build and Publish Web App
        run: msbuild SmartMove.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
     
        - name: Upload Artifact
          uses: actions/upload-artifact@v1.0.0
          with:
            name: published_webapp
            path: bin\Release\Publish