name: Mono

on: [push]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Install linux    
      run: |
            sudo apt-get update -y
            sudo apt-get install -y mono-xbuild wget openssl
            wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update -y
            sudo apt-get install -y apt-transport-https 
            sudo apt-get update -y
            sudo apt-get install -y dotnet-sdk-5.0
            sudo apt-get update -y 
            sudo apt-get install -y apt-transport-https
            sudo apt-get update -y
            sudo apt-get install -y aspnetcore-runtime-5.0
            sudo apt-get install -y dotnet-runtime-5.0
            sudo apt-get install monodevelop mono-mcs mono-devel
 -y

    - name: Run xbuild
      run : |
            xbuild /p:Configuration=Release SmartMove/SmartMove/SmartMove.csproj
      