name: Mono

# https://github.com/dotdevelop/dotdevelop/wiki/Linux-Mint-%28Ubuntu%29
# https://github.com/lextm/dotdevelop/blob/centos7/.github/workflows/monodevelop.yml
on: [push]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Install linux    
      run: |
            apt-get install -y sudo
            sudo apt install gnupg ca-certificates
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
            sudo apt update -y
            sudo apt-get update -y
            sudo apt-get install -y mono-xbuild wget openssl 
            wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update -y
            sudo apt-get install -y apt-transport-https 
            sudo apt-get update -y
            sudo apt-get install -y dotnet-sdk-5.0
            sudo apt-get update -y 
            sudo apt-get install -y apt-transport-https
            sudo apt-get update -y
            sudo apt-get install -y aspnetcore-runtime-5.0
            sudo apt-get install -y dotnet-runtime-5.0
            sudo apt-get install monodevelop mono-mcs mono-devel mono-devel mono-complete mono-dbg referenceassemblies-pcl ca-certificates-mono mono-xsp4 -y
            sudo apt-get install -y sed build-essential intltool fsharp gtk-sharp2
            sudo apt-get install -y software-properties-common

    - name: Run xbuild
      run : |
            xbuild /p:Configuration=Release SmartMove/SmartMove/SmartMove.csproj
      