name: Mono

# https://github.com/dotdevelop/dotdevelop/wiki/Linux-Mint-%28Ubuntu%29
# https://github.com/lextm/dotdevelop/blob/centos7/.github/workflows/monodevelop.yml
on: [push]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Install linux    
      run: |
        sudo apt-get update -y 
        sudo apt-get install -y sudo        
        sudo apt-get update -y 
        sudo apt-get install -y wget
        sudo apt install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common
        sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get install -y apt-transport-https
        sudo apt-get update -y 
        sudo apt-get install -y dotnet-sdk-5.0 dotnet-runtime-5.0 aspnetcore-runtime-5.0
        sudo apt-get install -y gnupg ca-certificates
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt-get update -y
        sudo apt-get install -y sed build-essential intltool
        sudo apt-get install -y software-properties-common mono-devel referenceassemblies-pcl ca-certificates-mono
        sudo apt-get install mono-complete -y
        sudo add-apt-repository ppa:git-core/ppa -y
        sudo apt-get update -y 
        sudo apt-get install -y git
        sudo apt-get install winetricks -y
        sudo winetricks dotnet45
      shell: bash
    - name: Run msbuild
      run : |
            msbuild -m /p:Configuration=Debug SmartMove.sln
      