name: SmartMove Sync
on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:


jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "chkp-yaelg/SmartMove"
          source_branch: "refs/tags/*"
          destination_repo: "ofirshi/SmartMove"
          destination_branch: "refs/tags/*"
          #ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          #destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`

